### PR TITLE
Refactor of Redrock MPI

### PR DESCRIPTION
**Pull request by tskisner**
This is a substantial refactor that supports a more traditional MPI software design.  MPI is still optional though, and the multiprocessing case has comparable performance on a single node.  This pull request will probably need to be manually merged (which I am happy to do) as well as squashed a bit first.  However, I wanted to open this to allow for further comments and feedback beyond what Julien and Stephen have already given.

I have tested the DESI wrapper for both the MPI and multiprocessing cases, and have also tested the BOSS MPI and multiprocessing wrappers on a single input.  Obviously more testing would be better before merging, in particular making sure that masking and other features have been successfully ported to this branch.

The unit tests are up to date, but I did not convert the rrspeedtest script.

### CODE REVIEW

**Comment by sbailey** [comment]
Unfortunately this is a pretty significant performance regression on large files.  Testing with /project/projectdirs//desi/datachallenge/reference_runs/17.12/spectro/redux/mini/spectra-64/53/5305/spectra-64-5305.fits (copied to $SCRATCH), which is 1.9G containing 6008 spectra of 2784 targets:

branch   | parallelism | runtime [min] | scale
-------- | ----------- | ------------- | -----
master   | multiprocessing | 20.7 |
refactor | multiprocessing | 44.5 | 2.1x slower
refactor | MPI             | 33.4 | 1.6x slower

Exact commands and logs are below.  It's not just a matter of slow initial I/O -- the individual zscan steps after everything is in memory are consistently slower, and reproducible.  The refactor multiprocessing version was also odd that the first template STAR:F took 10x longer than other stellar templates in both test runs even though they are doing the same number of redshifts, eigenvectors, and targets.  That difference represent much (but not all) of the runtime difference between refactor branch MPI vs. multiprocessing.

With a small file, the trend is reversed, however.  Using spectra-64-5272.fits, 
which is 55M containing 176 spectra of 176 targets:

branch   | parallelism | runtime [min] | scale
-------- | ----------- | ------------- | -----
master   | multiprocessing | 1.8 |
refactor | multiprocessing | 1.5 | 1.2x faster
refactor | MPI             | 1.0 | 1.8x faster

Although this branch does fix the MPI memory limitations by having a more MPI-centric style of dataflow, it still doesn't address the core problem of crashing when running at scale (based on tests by @julienguy; I haven't run that myself to report details here).  The performance regressions are significant enough that we should resolve those before accepting this as a refactor in the right direction even if it doesn't fully solve the scaling problems.  At minimum I would expect that the multiprocessing parallelism should have the same performance even if MPI is temporarily worse.

And in the meantime we need to coordinate how to not block other redrock work like PR #65 and other recent tickets.  @tskisner @julienguy let's analog chat on Tuesday about the roadmap for this refactor branch.

## Details ##

Initial setup using my redrock git clone checked out to either master or refactor branch
```
source /project/projectdirs/desi/software/desi_environment.sh 17.12
module swap redrock/sjb
salloc -N 1 -t 4:00:00 -C haswell -q interactive
cd $SCRATCH/rrtest/refactor
```

Commands / logs (swapping between redrock versions in between).  Second runs were done after the full set of 3 initial runs with different code versions / options.  Stripping out the "progress XX%" lines for brevity.
```
#-------------------------------------------------------------------------
#- master multiprocessing

<cori refactor> time rrdesi spectra-64-5305.fits --ncpu 32 -o rr-master-mp.fits --zbest zbest-master-mp.fits
INFO: reading targets
INFO: reading templates
DEBUG: Can't find redshift range info in template file /global/cscratch1/sd/sjbailey/desi/code/redrock-templates/rrtemplate-star-F.fits, using default values
DEBUG: Can't find redshift range info in template file /global/cscratch1/sd/sjbailey/desi/code/redrock-templates/rrtemplate-star-B.fits, using default values
DEBUG: Can't find redshift range info in template file /global/cscratch1/sd/sjbailey/desi/code/redrock-templates/rrtemplate-qso.fits, using default values
DEBUG: Can't find redshift range info in template file /global/cscratch1/sd/sjbailey/desi/code/redrock-templates/rrtemplate-star-G.fits, using default values
DEBUG: Can't find redshift range info in template file /global/cscratch1/sd/sjbailey/desi/code/redrock-templates/rrtemplate-star-M.fits, using default values
DEBUG: Can't find redshift range info in template file /global/cscratch1/sd/sjbailey/desi/code/redrock-templates/rrtemplate-galaxy.fits, using default values
DEBUG: Can't find redshift range info in template file /global/cscratch1/sd/sjbailey/desi/code/redrock-templates/rrtemplate-star-K.fits, using default values
DEBUG: Can't find redshift range info in template file /global/cscratch1/sd/sjbailey/desi/code/redrock-templates/rrtemplate-star-A.fits, using default values
INFO: using multiprocessing with 32 cores
DEBUG: PID 56088 STAR:F zscan in 34.1 seconds
DEBUG: PID 56088 STAR:F fitz in 24.3 seconds
DEBUG: PID 56088 STAR:G zscan in 34.1 seconds
DEBUG: PID 56088 STAR:G fitz in 25.2 seconds
DEBUG: PID 56088 QSO zscan in 189.1 seconds
DEBUG: PID 56088 QSO fitz in 31.7 seconds
DEBUG: PID 56088 GALAXY zscan in 373.4 seconds
DEBUG: PID 56088 GALAXY fitz in 59.9 seconds
DEBUG: PID 56088 STAR:M zscan in 34.6 seconds
DEBUG: PID 56088 STAR:M fitz in 26.6 seconds
DEBUG: PID 56088 STAR:A zscan in 35.7 seconds
DEBUG: PID 56088 STAR:A fitz in 25.3 seconds
DEBUG: PID 56088 STAR:K zscan in 36.2 seconds
DEBUG: PID 56088 STAR:K fitz in 25.3 seconds
DEBUG: PID 56088 STAR:B zscan in 34.5 seconds
DEBUG: PID 56088 STAR:B fitz in 27.4 seconds
INFO: writing rr-master-mp.fits
INFO: writing zbest-master-mp.fits
INFO: finished spectra-64-5305.fits in 1232.9 seconds

real	20m40.155s
user	436m18.568s
sys	4m41.492s

#- Second run
INFO: finished spectra-64-5305.fits in 1238.5 seconds
real	20m46.513s

#-------------------------------------------------------------------------
#- refactor multiprocessing

<cori refactor> time rrdesi spectra-64-5305.fits --mp 32 -o rr-refactor-mp.fits --zbest zbest-refactor-mp.fits
Running with 32 processes
Loading targets...
Read and distribution of 2784 targets: 77.0 seconds
DEBUG: Can't find redshift range info in template file /global/cscratch1/sd/sjbailey/desi/code/redrock-templates/rrtemplate-star-F.fits, using default values
DEBUG: Can't find redshift range info in template file /global/cscratch1/sd/sjbailey/desi/code/redrock-templates/rrtemplate-star-B.fits, using default values
DEBUG: Can't find redshift range info in template file /global/cscratch1/sd/sjbailey/desi/code/redrock-templates/rrtemplate-qso.fits, using default values
DEBUG: Can't find redshift range info in template file /global/cscratch1/sd/sjbailey/desi/code/redrock-templates/rrtemplate-star-G.fits, using default values
DEBUG: Can't find redshift range info in template file /global/cscratch1/sd/sjbailey/desi/code/redrock-templates/rrtemplate-star-M.fits, using default values
DEBUG: Can't find redshift range info in template file /global/cscratch1/sd/sjbailey/desi/code/redrock-templates/rrtemplate-galaxy.fits, using default values
DEBUG: Can't find redshift range info in template file /global/cscratch1/sd/sjbailey/desi/code/redrock-templates/rrtemplate-star-K.fits, using default values
DEBUG: Can't find redshift range info in template file /global/cscratch1/sd/sjbailey/desi/code/redrock-templates/rrtemplate-star-A.fits, using default values
Read and broadcast of 8 templates: 0.7 seconds
Rebinning templates: 30.6 seconds
Computing redshifts
  Scanning redshifts for template STAR:F
    Finished in: 505.0 seconds
  Scanning redshifts for template STAR:B
    Finished in: 48.7 seconds
  Scanning redshifts for template QSO
    Finished in: 399.3 seconds
  Scanning redshifts for template STAR:G
    Finished in: 48.8 seconds
  Scanning redshifts for template STAR:M
    Finished in: 49.0 seconds
  Scanning redshifts for template GALAXY
    Finished in: 1012.6 seconds
  Scanning redshifts for template STAR:K
    Finished in: 47.3 seconds
  Scanning redshifts for template STAR:A
    Finished in: 48.1 seconds
  Finding best fits for template STAR:F
    Finished in: 30.1 seconds
  Finding best fits for template STAR:B
    Finished in: 28.0 seconds
  Finding best fits for template QSO
    Finished in: 30.4 seconds
  Finding best fits for template STAR:G
    Finished in: 25.5 seconds
  Finding best fits for template STAR:M
    Finished in: 30.8 seconds
  Finding best fits for template GALAXY
    Finished in: 74.3 seconds
  Finding best fits for template STAR:K
    Finished in: 25.3 seconds
  Finding best fits for template STAR:A
    Finished in: 25.8 seconds
Computing redshifts took: 2506.2 seconds
Writing zscan data took: 7.7 seconds
Writing zbest data took: 32.8 seconds
Total run time: 2655.0 seconds

real	44m29.226s
user	568m9.416s
sys	9m22.176s

#-------------------------------------------------------------------------
#- refactor MPI

<cori refactor> time srun -n 32 -c 2 rrdesi_mpi spectra-64-5305.fits -o rr-refactor-mpi.fits --zbest zbest-refactor-mpi.fits
Running with 32 processes
Loading targets...
Read and distribution of 2784 targets: 37.6 seconds
DEBUG: Can't find redshift range info in template file /global/cscratch1/sd/sjbailey/desi/code/redrock-templates/rrtemplate-star-F.fits, using default values
DEBUG: Can't find redshift range info in template file /global/cscratch1/sd/sjbailey/desi/code/redrock-templates/rrtemplate-star-B.fits, using default values
DEBUG: Can't find redshift range info in template file /global/cscratch1/sd/sjbailey/desi/code/redrock-templates/rrtemplate-qso.fits, using default values
DEBUG: Can't find redshift range info in template file /global/cscratch1/sd/sjbailey/desi/code/redrock-templates/rrtemplate-star-G.fits, using default values
DEBUG: Can't find redshift range info in template file /global/cscratch1/sd/sjbailey/desi/code/redrock-templates/rrtemplate-star-M.fits, using default values
DEBUG: Can't find redshift range info in template file /global/cscratch1/sd/sjbailey/desi/code/redrock-templates/rrtemplate-galaxy.fits, using default values
DEBUG: Can't find redshift range info in template file /global/cscratch1/sd/sjbailey/desi/code/redrock-templates/rrtemplate-star-K.fits, using default values
DEBUG: Can't find redshift range info in template file /global/cscratch1/sd/sjbailey/desi/code/redrock-templates/rrtemplate-star-A.fits, using default values
Read and broadcast of 8 templates: 0.4 seconds
Rebinning templates: 1.2 seconds
Computing redshifts
  Scanning redshifts for template STAR:F
    Finished in: 42.2 seconds
  Scanning redshifts for template STAR:B
    Finished in: 42.3 seconds
  Scanning redshifts for template QSO
    Finished in: 364.1 seconds
  Scanning redshifts for template STAR:G
    Finished in: 42.8 seconds
  Scanning redshifts for template STAR:M
    Finished in: 42.8 seconds
  Scanning redshifts for template GALAXY
    Finished in: 929.0 seconds
  Scanning redshifts for template STAR:K
    Finished in: 43.1 seconds
  Scanning redshifts for template STAR:A
    Finished in: 43.0 seconds
  Finding best fits for template STAR:F
    Finished in: 18.9 seconds
  Finding best fits for template STAR:B
    Finished in: 20.7 seconds
  Finding best fits for template QSO
    Finished in: 23.4 seconds
  Finding best fits for template STAR:G
    Finished in: 19.0 seconds
  Finding best fits for template STAR:M
    Finished in: 23.1 seconds
  Finding best fits for template GALAXY
    Finished in: 65.9 seconds
  Finding best fits for template STAR:K
    Finished in: 18.6 seconds
  Finding best fits for template STAR:A
    Finished in: 19.7 seconds
Computing redshifts took: 1895.8 seconds
Writing zscan data took: 9.2 seconds
Writing zbest data took: 41.8 seconds
Total run time: 1985.9 seconds

real	33m23.389s
user	0m0.052s
sys	0m0.020s

#----------
Second run with --cpu_bind=cores

Computing redshifts took: 1886.7 seconds
Writing zscan data took: 8.7 seconds
Writing zbest data took: 42.4 seconds
Total run time: 1977.0 seconds

real	33m13.364s
```

**Comment by tskisner** [comment]
Interesting...  I did compare performance to the master branch on one of the "medium" sized files that was about 600MB.  I'll go dig up those numbers to verify.  Obviously it would be good to understand any differences.

My understanding is that the recent segfault Julien observed was something different than running out of memory (which was the problem with original MPI versions of redrock).  The further debugging run you did seemed to indicate that some spectra files with a single target were causing one type of crash, but that should have been fixed by 43d40db53b709cf3a766eed543201e03d7b93d82.

Looking forward to clarifying all this tomorrow.

**Comment by tskisner** [comment]
@sbailey discovered a bug / mistake in this branch- the coadds were being computed but never used.  I just pushed a fix for that and then ran a test with a "smallish" spectra file (406 targets, using coadds).  This was again using a newer version of desiconda that uses IDP rather than stock anaconda.  These jobs produced the following output (ignoring extraneous lines):
```
# Master, multiprocessing

Starting slurm script at Tue Jan 16 19:56:43 PST 2018        
srun -n 1 -N 1 -c 2 rrdesi --output rrdesi-master-64-11741.h5 --zbest zbest-master-64-11741.fits --ncpu 32 spectra-64-11741.fits                        
INFO: reading targets                                                       
ERROR: Target 6351955475652311492 on spectra-64-11741.fits has no good spectra                                                                          
INFO: reading templates                                                             
INFO: using multiprocessing with 32 cores                                   
DEBUG: PID 9616 STAR:F zscan in 10.7 seconds                                
DEBUG: PID 9616 STAR:F fitz in 7.0 seconds                                  
DEBUG: PID 9616 STAR:G zscan in 8.7 seconds                                 
DEBUG: PID 9616 STAR:G fitz in 7.4 seconds                                  
DEBUG: PID 9616 STAR:B zscan in 8.8 seconds                                 
DEBUG: PID 9616 STAR:B fitz in 7.3 seconds                                  
DEBUG: PID 9616 STAR:K zscan in 8.8 seconds                                 
DEBUG: PID 9616 STAR:K fitz in 7.3 seconds
DEBUG: PID 9616 QSO zscan in 44.4 seconds
DEBUG: PID 9616 QSO fitz in 9.5 seconds
DEBUG: PID 9616 GALAXY zscan in 109.5 seconds
DEBUG: PID 9616 GALAXY fitz in 18.6 seconds
DEBUG: PID 9616 STAR:A zscan in 8.8 seconds
DEBUG: PID 9616 STAR:A fitz in 7.5 seconds
DEBUG: PID 9616 STAR:M zscan in 8.7 seconds
DEBUG: PID 9616 STAR:M fitz in 7.5 seconds
INFO: writing rrdesi-master-64-11741.h5
INFO: writing zbest-master-64-11741.fits
INFO: finished spectra-64-11741.fits in 319.0 seconds

real    5m48.234s
user    0m0.048s
sys     0m0.012s
```
And from the refactor branch
```
# Refactor, multiprocessing

Starting slurm script at Tue Jan 16 19:55:30 PST 2018                         
srun -n 1 -N 1 -c 2 rrdesi --output rrdesi-multi-64-11741.h5 --zbest zbest-multi-64-11741.fits --mp 32 spectra-64-11741.fits                                
Running with 32 processes                                                     
Loading targets...                                                            
Read and distribution of 406 targets: 7.8 seconds                             
Read and broadcast of 8 templates: 1.2 seconds                                
Rebinning templates: 10.8 seconds                                             
Computing redshifts                                                           
  Scanning redshifts for template STAR:F                                      
    Finished in: 22.4 seconds                                                 
  Scanning redshifts for template STAR:G                                      
    Finished in: 3.2 seconds                                                  
  Scanning redshifts for template STAR:B                                      
    Finished in: 3.2 seconds                                                  
  Scanning redshifts for template STAR:K                                      
    Finished in: 3.2 seconds                                                  
  Scanning redshifts for template QSO                                         
    Finished in: 24.9 seconds                                                 
  Scanning redshifts for template GALAXY                                      
    Finished in: 69.4 seconds                                                 
  Scanning redshifts for template STAR:A                                      
    Finished in: 3.2 seconds                                                  
  Scanning redshifts for template STAR:M                                      
    Finished in: 3.2 seconds                                                  
  Finding best fits for template STAR:F                                       
    Finished in: 4.6 seconds                                                  
  Finding best fits for template STAR:G                                       
    Finished in: 4.4 seconds                                                  
  Finding best fits for template STAR:B                                       
    Finished in: 4.9 seconds                                                  
  Finding best fits for template STAR:K                                       
    Finished in: 4.7 seconds                                                  
  Finding best fits for template QSO                                          
    Finished in: 4.2 seconds
  Finding best fits for template GALAXY
    Finished in: 14.5 seconds
  Finding best fits for template STAR:A
    Finished in: 4.7 seconds
  Finding best fits for template STAR:M
    Finished in: 4.9 seconds
Computing redshifts took: 190.6 seconds
Writing zscan data took: 1.5 seconds
Writing zbest data took: 0.4 seconds
Total run time: 212.4 seconds

real    3m48.876s
user    0m0.048s
sys     0m0.032s
```
And
```
# Refactor, MPI

Starting slurm script at Tue Jan 16 20:00:52 PST 2018                         
srun --cpu_bind=cores -n 32 -N 1 -c 2 rrdesi_mpi --output rrdesi-mpi-64-11741.h5 --zbest zbest-mpi-64-11741.fits spectra-64-11741.fits                      
Running with 32 processes                                                     
Loading targets...                                                            
Read and distribution of 406 targets: 3.5 seconds                             
Read and broadcast of 8 templates: 6.8 seconds                                
Rebinning templates: 4.9 seconds                                              
Computing redshifts                                                           
  Scanning redshifts for template STAR:F                                      
    Finished in: 2.0 seconds                                                  
  Scanning redshifts for template STAR:G                                      
    Finished in: 1.5 seconds                                                  
  Scanning redshifts for template STAR:B                                      
    Finished in: 1.5 seconds                                                  
  Scanning redshifts for template STAR:K                                      
    Finished in: 1.5 seconds                                                  
  Scanning redshifts for template QSO                                         
    Finished in: 10.8 seconds                                                 
  Scanning redshifts for template GALAXY                                      
    Finished in: 26.6 seconds                                                 
  Scanning redshifts for template STAR:A                                      
    Finished in: 1.4 seconds                                                  
  Scanning redshifts for template STAR:M                                      
    Finished in: 1.4 seconds                                                  
  Finding best fits for template STAR:F                                       
    Finished in: 2.3 seconds                                                  
  Finding best fits for template STAR:G                                       
    Finished in: 1.8 seconds                                                  
  Finding best fits for template STAR:B                                       
    Finished in: 2.0 seconds                                                  
  Finding best fits for template STAR:K                                       
    Finished in: 1.8 seconds                                                  
  Finding best fits for template QSO                                          
    Finished in: 1.5 seconds
  Finding best fits for template GALAXY
    Finished in: 6.2 seconds
  Finding best fits for template STAR:A
    Finished in: 1.8 seconds
  Finding best fits for template STAR:M
    Finished in: 2.0 seconds
Computing redshifts took: 84.7 seconds
Writing zscan data took: 5.9 seconds
Writing zbest data took: 0.6 seconds
Total run time: 106.4 seconds

real    4m4.201s
user    0m0.052s
sys     0m0.028s
```
The astute reader will note that something is fishy- the elapsed times for the various steps in the refactor branch (computed with differences of time.time() values) don't seem to add up to the value reported by the "time" command line tool.  The discrepancy seems too big to be due to python startup time.  This should be investigated further.

**Comment by tskisner** [comment]
Ok, I will proceed with fixes and rebasing.

**Comment by tskisner** [comment]
sphinx docs failed to build since source files have changed.  Will fix along with metadata issue.

**Comment by tskisner** [comment]
Ah, this is actually a python3 vs python2 change in OrderedDict.

**Comment by tskisner** [comment]
@sbailey and @julienguy, I think this is ready for any final testing now.  Metadata propagation seems all good.

**Pull request merged**
