### PR TITLE
sort targetids

### PR DESCRIPTION
**Pull request by londumas**
Fix issue https://github.com/desihub/redrock/issues/138, by sorting targetids.
However, this doesn't fix the reason why `zfind.py::zfind()` can mix information in the first place.
Tested on rrboss and on desi-minitest.

### CODE REVIEW

**Comment by sbailey** [comment]
Good catch on finding the bug.  Does this PR fix the underlying problem, or just make the outputs reproducible regardless of the input order of the targetids?  i.e. is it possible that zfind is still mixing target information and now just producing reproducibly wrong results for some inputs?  I'm not sure what is meant by "this doesn't fix the reason why zfind.py::zfind() can mix information in the first place."

**Comment by londumas** [comment]
>  Does this PR fix the underlying problem

no
> is it possible that zfind is still mixing target information and now just producing reproducibly wrong results for some inputs?

yes, it is possible, but improbable.
Still we should check what is happening in `zfind.py::zfind()` that mixes things.

**Comment by londumas** [comment]
Tested on `rrboss`, on `rrdesi` and on `rrdesi_mpi`. Works fine.

**Comment by londumas** [comment]
@sbailey, ready to be merged.

**Pull request merged**
