### PR TITLE
init of fix issue 49

### PR DESCRIPTION
**Pull request by londumas**
track number of degrees of freedom used in chi2 calculations
https://github.com/desihub/redrock/issues/49

Not finished.
@sbailey, could you tell me how to get the number of valid pixels if co-adding observations ?

### CODE REVIEW

**Comment by londumas** [comment]
@sbailey, also how to compare a fit by QSO with nparam=4 and a fit of galaxy with nparam=10?

**Comment by londumas** [comment]
@sbailey, I don't see where you replace the spectra by the coadded spectrum if the option is on.

**Comment by sbailey** [comment]
It's a bit of a hack.  See [redrock.external.desi lines 280-283](https://github.com/desihub/redrock/blob/master/py/redrock/external/desi.py#L280-L283) where it (optionally) replaces the full `target.spectra` array with the `target.coadd` array as part of reading in the data.  The downstream code thinks it is working with the spectra, unaware that those got replaced with a coadd.

**Comment by londumas** [comment]
@sbailey, ready to be merged.
Is ti ok for you?

**Pull request merged**
