### PR TITLE
fix issue 47

### PR DESCRIPTION
**Pull request by londumas**
Issue https://github.com/desihub/redrock/issues/47
SMALL_DELTA_CHI2 for different star templates

### CODE REVIEW

**Comment by sbailey** [comment]
Thanks for working on this, but I think we want a more generic solution that works for any of the redshifts, not just the 0th and 1st.  And following @djschlegel's comment in #47, we should consider doing it like BOSS and just not set SMALL_DELTA_CHI2 if two redshifts are within 1000 km/s even if they are different classes.  The exact number could be tuned and it isn't a specific physical reason, but it is pragmatically tuned for avoiding local false minima within the same template, and allowing two templates to agree on the redshift without clobbering each other with a SMALL_DELTA_CHI2.

**Comment by londumas** [comment]
Do you mean something like this?
```
            for i in range(len(tzfit)-1):
                cond = (tzfit['zwarn'][i] & ZW.SMALL_DELTA_CHI2)!=0
                cond &= (tzfit['zwarn'][i+1] & ZW.SMALL_DELTA_CHI2)==0
                cond &= (tzfit['spectype'][i]==tzfit['spectype'][i+1])
                cond &= (tzfit['subtype'][i]!=tzfit['subtype'][i+1])
                if cond: tzfit['zwarn'][i] -= ZW.SMALL_DELTA_CHI2
```

**Comment by djschlegel** [comment]
John- I think you want to be robust to the case where there could be many local minima within the arbitrary 1000 km/s range.  So, compare to the smallest chi2 outside that range.

**Comment by londumas** [comment]
@djschlegel, where does this arbitrary `1000 km/s` come from?

**Comment by djschlegel** [comment]
That's absolutely an arbitrary number.  It ought to be many sigma larger than the formal redshift errors  For BOSS, since our Poisson errors on the redshifts were ~80 km/s at the faint end, that was >10 sigma.  But if it's too large, then one would be ignoring false redshifts that we should be flagging as bad if another minimum is nearby -- in BOSS since we were searching galaxies across a redshift span of 1, that's a 0.3% effect.

One could argue whether this ought to be a decision that is made per-object.  For example, if a quasar had a redshift error of 500 km/s, should this number be larger for just that object?

**Comment by londumas** [comment]
@sbailey, you define dv in py/redrock/fitz.py as:
```
dv = (scipy.constants.speed_of_light/1000.) * (redshifts[imin] - zprev) / (1.+redshifts[imin])
```
I define it in py/redrock/zfind.py as:
```
dv = scipy.constants.speed_of_light/1000.*(tzfit['z'][i]-tzfit['z'][i+1])/(1.+(tzfit['z'][i]+tzfit['z'][i+1])/2.)
```

what do you prefere? the min_z or the mean_z?

**Comment by sbailey** [comment]
I'll actually propose a 3rd option:
```python
def get_dv(z, zref):
    '''returns velocity difference in km/s for two redshifts'''
    c = (scipy.constants.speed_of_light/1000.) #- km/s
    dv = c * (z - zref) / (1.0 + zref)
    return dv
```
Both places where we need `dv` should call that.  This form of the function has the advantage that `zref` could refer to a true redshift.

**Comment by londumas** [comment]
@sbailey, good idea.
in both these cases would you set `zref`to z_min, z_max or z_mean ?

**Comment by londumas** [comment]
@sbailey, where should we put this function?

**Comment by sbailey** [comment]
Let's put it in `redrock.fitz.get_dv(z, zref)` and call it with zref = the redshift with the smaller chi2 and z = the redshift with the larger chi2.

**Pull request merged**
