### PR TITLE
Apply codacy recomendations

### PR DESCRIPTION
**Pull request by londumas**
Apply codacy recommendations from codacy.com, allowing to remove useless imports and other small imperfections in the code.
Testing if everything works on rrdesi and on rrboss.
I will tell you when it is ready to be merged.

### CODE REVIEW

**Comment by londumas** [comment]
Works on rrdesi, rrdes_mpi and rrboss. @sbailey, ready to be reviewed and merged.

**Comment by londumas** [comment]
@sbailey, One issue that Codacy will continue to say is the following unused variable.
But we can neglect it since this is aiming at at a test.
```
py/redrock/test/test_rebin.py
Unused variable 'summ'
summ = rebin.trapz_rebin(x, y, edges=[0.5, 8.3])[0]
```

**Comment by sbailey** [comment]
Codacy are recommendations not requirements, so ok if we sometimes disagree with it.

**Comment by londumas** [comment]
@sbailey, agreed. Let's wait for every test to run and let's see.

**Pull request merged**
