### PR TITLE
Add archetypes

### PR DESCRIPTION
**Pull request by londumas**
Work in progress at adding an archetype logic to redrock PCAs.
The current version does the work on 1 boss plate:
- add a `bin/rrarchetypes` to create archetypes for galaxies and stars from desisim
- does all the job in achetypes.py
- the archetype have their related sub-type: `ELG`, 'BGS', 'LRG', 'A', 'WB', ...
- it is very long for reasons I don't understand. The archetype are composed of 723 galaxies, 625 quasars and 142 stars.

The current version is lacking few things:
- compute chi2 with resolution matrix
- keep coefficients
- remove hard-codded degree of Legendre polynomial
- allow user to use or not archetypes and to change the path where they are read from
- nothing is currently done for spectra where the best fit has a negative coefficient

This commit corrects also an issue related to `znum` in `zfin.py` when we would have `znum in [0,1,2,4,5,6,7,8,9]` for example (i.e. missing the `3`).

### CODE REVIEW

**Comment by londumas** [comment]
@sbailey, it works quite well but it is very long. It seems to come from the evaluation of the archetype at the proper redshift. I don't see how that is since redrock does it a lot very fast in `rebin_template` and it seems to go very fast. Am-I dealing too badly with memory? Or doing something else badly ?

**Comment by londumas** [comment]
The current PR does a good job, along with redrock-archetypes on desihub.
Some work has to be done on Quasar archetypes.
Could you have a look at the code @sbailey?
Comparing Redrock(Master) to SDSS-truth table:
```
                   ntarg   good  fail  miss  lost
GALAXY              5111  97.22  0.82  0.72  1.23
QSO                   89  83.15  7.87  3.37  5.62
STAR                 302  91.06  5.63  0.33  2.98

                         | GALAXY  | QSO     | STAR    | 
GALAXY              5111 |  99.45 |   0.49 |   0.06 | 
QSO                   89 |  13.48 |  86.52 |   0.00 | 
STAR                 302 |   6.29 |   2.32 |  91.39 |
```
Comparing Redrock(Branch) to SDSS-truth table:
```
                   ntarg   good  fail  miss  lost
GALAXY              5111  97.65  0.88  0.45  1.02
QSO                   89  92.13  3.37  1.12  3.37
STAR                 302  95.70  1.99  1.99  0.33

                         | GALAXY  | QSO     | STAR    | 
GALAXY              5111 |  98.85 |   0.61 |   0.55 | 
QSO                   89 |   8.99 |  89.89 |   1.12 | 
STAR                 302 |   1.66 |   0.33 |  98.01 |
```

**Comment by londumas** [comment]
I have constructed new quasar archetype. I fit SDSS data with quasar PCAs, this gives me a list of
spectra I can construct archetype from.
I also added SDSS stars when building stellar archetypes.
The result is even better.
Looking at the failing modes, it seems we are reaching the limit of the truth tables.

Comparing Redrock(Master) to SDSS-truth table:
```
                   ntarg   good  fail  miss  lost
GALAXY              5111  97.22  0.82  0.72  1.23
QSO                   89  83.15  7.87  3.37  5.62
STAR                 302  91.06  5.63  0.33  2.98

                         | GALAXY  | QSO     | STAR    | 
GALAXY              5111 |  99.45 |   0.49 |   0.06 | 
QSO                   89 |  13.48 |  86.52 |   0.00 | 
STAR                 302 |   6.29 |   2.32 |  91.39 |
```
Comparing Redrock(Branch) to SDSS-truth table:
```
                   ntarg   good  fail  miss  lost
GALAXY              5111  97.55  0.92  0.55  0.98
QSO                   89  91.01  5.62  1.12  2.25
STAR                 302  97.35  1.32  0.33  0.99

                         | GALAXY  | QSO     | STAR    | 
GALAXY              5111 |  98.06 |   1.62 |   0.31 | 
QSO                   89 |   3.37 |  96.63 |   0.00 | 
STAR                 302 |   1.66 |   0.33 |  98.01 |
```

**Comment by londumas** [comment]
Looking at the minitests, it is doing better for stars and galaxies. Less good for sky fibers.

```
redrock = Master
                   ntarg   good  fail  miss  lost
GALAXY              9373  97.89  0.49  0.65  0.97
QSO                 1167  99.06  0.60  0.26  0.09
SKY                  963   0.00 16.41  0.00 83.59
STAR                 647  74.03  6.34  0.62 19.01
WD                    19  89.47 10.53  0.00  0.00

                         | GALAXY  | QSO     | STAR    | 
GALAXY              9221 |  100.00 |   0.00 |   0.00 | 
QSO                 1163 |   0.52 |  99.48 |   0.00 | 
SKY                  158 |  100.00 |   0.00 |   0.00 | 
STAR                 520 |   7.88 |   0.00 |  92.12 | 
WD                    19 |  10.53 |   0.00 |  89.47 |

redrock+archetype = Branch
                   ntarg   good  fail  miss  lost
GALAXY              9373  98.51  0.35  0.32  0.82
QSO                 1167  99.31  0.43  0.26  0.00
SKY                  963   0.00 21.18  1.66 77.15
STAR                 647  76.20  6.03  4.33 13.45
WD                    19  94.74  0.00  5.26  0.00

                         | GALAXY  | QSO     | STAR    | 
GALAXY              9266 |  99.92 |   0.06 |   0.01 | 
QSO                 1164 |   0.00 |  100.00 |   0.00 | 
SKY                  204 |  81.86 |  18.14 |   0.00 | 
STAR                 532 |   6.77 |   0.56 |  92.67 | 
WD                    18 |   0.00 |   0.00 |  100.00 |
```

**Comment by londumas** [comment]
fixes issue https://github.com/desihub/redrock/issues/57

**Comment by londumas** [comment]
@sbailey, there might be an issue with the version of h5py used. It doesn't know about `AttributeError: module 'h5py' has no attribute 'highlevel'`. when the version I use does: I use '2.6.0'.

**Comment by londumas** [comment]
@sbailey, ready to be reviewed

**Comment by sbailey** [comment]
@londumas thanks for your patience while I caught up with reviewing this.  Looks good.  I made a cosmetic change to simplify the command line options: if you specify `--archetypes FILE_OR_DIR` it will use archetypes, and if you don't give that option it won't.  i.e. no need to specify both `--archetypes` and `--use-archetype` (and have an ambiguous state of what to do if the user had said `--use-archetype` without giving `--archetype`).

If you agree, go ahead and merge.  If you disagree, let me know why and we can revert or further update.

**Comment by londumas** [comment]
The idea, was that in a similar way as the redrock-templates, if you don't give a path then the path is `None` and it reads it from the default path. THis feature of redrock-templates is very nce, that is why I added it to redrock-archetypes. Also do you want the archetype to be used by default or not ?

**Comment by sbailey** [comment]
I'd like to keep this as non-default for the next tag and major desi code release.  All your tables look good, but I'd like to look at this more closely when I'm in a less rushed state before making this fairly major change in the redrock methodology.

After it is default, we can use `$RR_ARCHETYPE_DIR` for the default location, use `--archetypes` to override that, and a new option `--no-archetypes` to turn it off.  But that is for the future.  Merging now to get this option in place.

**Pull request merged**
