### PR TITLE
add broadbands

### PR DESCRIPTION
**Pull request by londumas**
Add an option to add broadbands to the templates. The parameter is the number of different broadband coefficients.
```
bb_deg_i = ( (w-<w>)/<w> )**i
```
Tested on eboss data and works well. It removes the sky fibers that were mostly previously flagged as galaxies.
Testing on desi

fix issue https://github.com/desihub/redrock/issues/39

### CODE REVIEW

**Comment by londumas** [comment]
Works on desi data
We might want to set it to 0 or 1 by default instead of None.
We would need to study on some plates the best to do.

**Comment by ngbusca** [comment]
@londumas it looks like you added the power laws as extra pca components (i.e. in the rest frame and before convolution by the reaolutiob)? I understood from issue #39 @sbailey and @jguy were against this kind of implementation...

**Comment by ngbusca** [comment]
@londumas another issue is that when fitting individual exposures, while the coefficients of the pca are the same for all exposures of the same spectrum, but the coeffs of the power law might be different...

**Comment by londumas** [comment]
@ngbusca, I understand better now the discussions in https://github.com/desihub/redrock/issues/39

**Pull request closed without merging**
