### PR TITLE
chi2 penalize negative [OIII] flux

### PR DESCRIPTION
**Pull request by RaffaellaCapasso**
First changes to chi2 penalty for negative [OIII] line. This is connected to issue 215.

### CODE REVIEW

**Comment by sbailey** [comment]
Thanks for this PR.  I put a few comments inline.  Please also add some info to this PR text about how often the negative [OIII] penalty causes redrock to chose a different solution, and some examples.

Note: the negative [OII] penalty was completely ad-hoc, and was added to avoid an early failure mode tested on simulations and eBOSS data.  An equivalent negative [OIII] penalty may require a different weight or offset, but that will depend upon how rare this case is, and whether the cases are switching from bad to good, or just bad to different bad, or if it is just triggering on noise fluctuations.

**Comment by RaffaellaCapasso** [comment]
Thanks for the notes! I added more details to the [issue 215](https://github.com/desihub/redrock/issues/215).

**Comment by sbailey** [comment]
@RaffaellaCapasso it appears that you are using the continuum when deciding if a line is negative, but not for the actual chi2 penalty, which means that a line like this would actually upweight the fit instead of penalizing it since it is negative relative to the continuum but positive relative to 0:

image

It also looks like you haven't yet put a wavelength coverage check that you are only penalizing [OIII] when it is covered by the data.

I see in issue #215 that you said "over 86 original fuji targets with negative OIII line, only 13 retained this feature in their best-fit template".  Please run tests with a much larger number of targets, including ones that did not have a negative [OIII] in the first place to confirm what fraction of targets are impacted.  e.g. "testing on 50000 targets (10 tiles), X% changed their best fit redshift..."

Please also post a plot showing your choice of [OIII] integration range and continuum ranges compared to example bad fits in restframe wavelengths, e.g. from #215 but converted to restframe and showing the integration and continuum side bands:
image

**Comment by RaffaellaCapasso** [comment]
@sbailey Thanks for your comments! I have now modified the penalty so that it takes the continuum into account. I have also added a wavelength coverage check. 

Here is the plot you asked for:

Screenshot 2022-08-18 at 15 38 12

The red area is the selected [OIII] range, the green ones are the areas in which the continuum is calculated. 

I run the new code on 10 tiles, as suggested. These are the percentages of targets that changed their best-fit redshift:

- 5% of all targets (SPECTYPE == GALAXY, OBJTYPE == TGT )
- 3% of good targets (SPECTYPE == GALAXY, OBJTYPE == TGT, ZWARN==0)
- 2% of extra good targets (SPECTYPE == GALAXY, OBJTYPE == TGT, ZWARN==0 and DELTACHI2>25)

The plots below show some examples of targets that changed their best-fit redshift. Red is the original best-fit, blue is the original second best, green is the new best. In a few cases the new best-fit corresponds to the old second best (thus the blue does not appear as it's overwritten by the green one).

**Comment by sbailey** [comment]
This is not converging in time for Iron, so I've removed this from the Iron project task list.

We need a more comprehensive study of why so many targets are changing; we expect ZWARN=0 DELTACHI2>25 targets to have >98% purity, so changes of 2% is large compared to the ~2% that we expect to be bad, especially since the spot checks aren't an obvious "even bad case is now good".

**Comment by sbailey** [comment]
I'm closing this PR since it will be superseded by other work (significance based-penalty; see Daniel Gruen DESI data presentation on the wiki at DataSystems/Telecons/2022-11-08).

**Pull request closed without merging**
