### PR TITLE
fix when matrix is not positive definite

### PR DESCRIPTION
**Pull request by londumas**
fix when matrix is not positive definite by catching the error and setting the chi2 to nan.
The rest of the code set then the BAD_MINFIT ZWARNING flag
fix issue https://github.com/desihub/redrock/issues/108

### CODE REVIEW

**Comment by londumas** [comment]
The code raise the following error, I am investigating.
```
<me>/Programs/desi/code/redrock/py/redrock/fitz.py:61: RuntimeWarning: invalid value encountered in less_equal
  ii = np.where(np.r_[True, x[1:]<=x[:-1]] & np.r_[x[:-1]<=x[1:], True])[0]
```

**Comment by ngbusca** [comment]
@londumas in case it helps... this means that you are comparing against nan, those comparisons will give `False`

**Comment by sbailey** [comment]
NaNs are often a pain; it might be better to just return a magic number like 9e99 instead.

**Comment by londumas** [comment]
@sbailey, I don't see where the error comes from.

**Comment by sbailey** [comment]
@londumas I made a small change to catch only `np.linalg.LinAlgError` instead of all exceptions.

@ngbusca you are right that this case comes from a target with two few pixels.  It does get flagged with the zwarn LITTLE_COVERAGE flag downstream, but in the current code it doesn't realize that it has too few pixels until the end instead of the beginning.  Better would be to to a pre-flight check to not bother trying to fit targets with too few pixels, but in the meantime this PR adds some robustness.

**Pull request merged**
